# Generated by Django 6.0.2 on 2026-04-07 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FlossFriends_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canvas',
            options={},
        ),
        migrations.AlterModelOptions(
            name='palette',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pattern',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sysdiagrams',
            options={},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={},
        ),
        migrations.AlterModelOptions(
            name='threadcalculation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='threadinventory',
            options={},
        ),
    ]
