# Generated by Django 6.0.2 on 2026-04-27 12:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlossFriends_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.AlterModelOptions(
            name='canvas',
            options={},
        ),
        migrations.AlterModelOptions(
            name='palette',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pattern',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sysdiagrams',
            options={},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={},
        ),
        migrations.AlterModelOptions(
            name='threadinventory',
            options={},
        ),
        migrations.AddField(
            model_name='customuser',
            name='token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pattern',
            name='is_public',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verification_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='canvas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlossFriends_project.canvas'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thread',
            name='palette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlossFriends_project.palette'),
        ),
        migrations.AlterField(
            model_name='threadinventory',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlossFriends_project.thread'),
        ),
        migrations.AlterField(
            model_name='threadinventory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='sysdiagrams',
            unique_together={('principal_id', 'name')},
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('favorite_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField()),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlossFriends_project.pattern')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Favorite',
                'unique_together': {('pattern', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField()),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlossFriends_project.pattern')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Like',
                'unique_together': {('pattern', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PatternCategory',
            fields=[
                ('patterncategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlossFriends_project.category')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlossFriends_project.pattern')),
            ],
            options={
                'db_table': 'PatternCategory',
            },
        ),
        migrations.AddField(
            model_name='pattern',
            name='categories',
            field=models.ManyToManyField(related_name='patterns', through='FlossFriends_project.PatternCategory', to='FlossFriends_project.category'),
        ),
        migrations.DeleteModel(
            name='Threadcalculation',
        ),
    ]
