# Generated by Django 6.0.2 on 2026-04-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlossFriends_project', '0002_category_alter_canvas_options_alter_palette_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='token_created_at',
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]
