# Generated by Django 6.0.2 on 2026-04-27 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FlossFriends_project', '0002_category_alter_canvas_options_alter_palette_options_and_more'),
    ]

    operations = []
